const regions = {
    minas: {
        title: "Minas Morgul",
        description: "Autrefois une grande cité peuplé par les Nazguls, cette dernière à été partiellement détruite et abandonnée lors de la Grande Guerre. <br> Elle est située dans les terres du nord, dans une véritable toundra. Des immenses ruines de ce châteaux d'un autre temps surplombes les montagnes autour de la plaine. <br><br> Après la mort de Pharra en l'an 104 AGW, le nouveau Roi des démons, Tom Sammartano, décida de s'allier avec les rares Nazguls toujours en vie. C'est ensemble qu'ils décidèrent de se lancer dans la construction d'un petit village où les survivants Démons et Nazguls pourraient vivre ensemble. <br> Pour l'heure, le village est encore en construction, l'objectif des Démons et des Nazguls et de reconstruire une véritable ville à partir des ruines de Minas Morgul et du nouveau village. Afin de devenir la prochaine grande ville du nord, comme Minas Morgul avait pu l'être autrefois."
    },
    ridranthic: {
        title: "Ridranthic",
        description: "Ridranthic est la ville des Golems de glace, elle à comme particularité d'être construire entièrement en glace et en neige compactée et presque aussi résistance que de la pierre. Les Golems de glace y vivent retranchés dans des quartiers représentants les différentes familles. <br><br> Chaque familles possèdent une grande maison avec leurs symboles respectifs. Ils vivent en harmonie mais la notion de famille est encore très présente dans la société de Ridranthic. Chacun ayant une vision différente de la vie ainsi que des buts et des spécialités différentes. <br> Il n'y a pas vraiment de guerres entre les familles mais des certaines formes de rivalités peuvent subsister. <br><br> Au frontières de chaque quartiers se trouvent des douves et canaux qui sont présents un peu partout dans la ville. Ils permettent ainsi à certains de leurs habitants de pouvoir naviguer entre les quartiers, rendant les déplacements parfois plus faciles. <br> Ils se déversent ensuite dans des rivières plus au sud qui elles même se déversent dans un fleuve qui lui se déverse dans la mer des léviathans. Rendant ainsi le commerce possible avec Lin. <br> Ces canaux sont aussi parfois des moyens d'accès à la partie sous terraine qui est très importante. Les sous terrains de Ridranthic sont aussi habités, ils consistent en plusieurs de réseaux interconnectés de cavernes glacés. Il est encore possible de s'y perdre mais une bonne majorité de ces grottes ont étés explorées et même habités. <br> En période de tempête de neige, les habitants qui ne sont pas des Golems de glace vont se réfugier dans ces grottes. Les Golems en ont donc profités pour établir des magasins sous terrains, accessibles aux visiteurs."
    },
    galadhbo: {
        title: "Galadhbo",
        description: "Galadhbo est la ville des Elfes Lumineux, implantée dans la forêt magique. Elle est constitués de maisons en bois construites au pieds d'arbres ou même directement sur des branches ou dans la cime des arbres. Une succession de petites maisonnettes très chaleureuses et charmantes reliées entre elles par des petits pontons. <br> La végétation y est maître en ces lieux, elle vit en symbiose avec ces habitants qui se servent des plantes pour la médecine qui est très développée. Mais aussi pour la magie et la spiritualité de la nature. <br> Le centre ville reste tout de même non loin de la lisière de la forêt. <br><br> Plus profondément dans la forêt, là où la lumière est moins présente, se trouve toujours des habitations. C'est ici que les Elfes lumineux les plus solitaires et les apprentis sorciers et mages viennent y habiter. C'est souvent dans ces lieux que les Elfes se préparent avant d'aller faire leur pèlerinage vers les arbres primordiaux. <br> Au bords de rivières qui vont en direction des arbres primordiaux, certains rapportent avoir vus de drôles de lumière à la surface de l'eau, comme des spectres d'un temps passé cherchant à communiquer avec les Elfes. <br><br> Au cœur de la forêt magique se trouvent les arbres primordiaux. Ce sont de grands arbres de différentes variétés qui ont pour la particularité d'y abriter des quantités absurdes de magie. Les légendes racontent que ces derniers sont les pères de toutes formes de vie végétales sur les terres d'Arzmania, d'où leur appellation d'arbres primordiaux. <br> Les jeunes Elfes ainsi que les apprentis mages et sorciers sont nombreux à partir en pèlerinage en ces terres ancestrales et sacrées. Certains viennent simplement prier au pied de ces arbres pour concentrer leur mana, tandis que d'autres rapportent avoir réussi à communiquer avec des êtres de l'au delà."
    },
    lin: {
        title: "Lin",
        description: "Lin est la ville des Ondins, elle est situé sur les côtes de la mer des Léviathans. À moitié sur la plage, à moitié sous l'eau, elle sert de point central au commerce mondial des terres d'Arzmania. <br> Les bâtiments ont pour particularités d'être tous faits à partir de marbre, d'or et de lapis lazuli. <br><br> La partie immergée de la ville quant à elle, est constituée de calcaire en plus du marbre. Cela consiste en de grandes tours sous marines qui sont aussi remplies d'eau à l'intérieur. Ils vivent avec les coraux et les poissons qu'ils s'amusent d'ailleurs à pêcher. Que ce soit pour le plaisir, pour s'alimenter ou bien pour le commerce. <br> C'est ici que les Ondins vivent leur vie de tout les jours. La partie émergée étant plutôt le côté commercial de la ville tandis que le côté immergé est réservé au résidentiel. <br><br> En continuant de naviguer à quelques kilomètres à l'Ouest dans la mer des Léviathans, il se trouve l'archipel sacré. Un petit village y a été construit à sa surface. C'est une île qui n'est pas très fréquentée. Dans les traditions des Ondins, c'est là que les anciens vont vivre les dernières années de leur vie, loin du commerce, loin de la guerre. Retournant à une vie plus simple et rudimentaire. <br> Il y a aussi de mystérieux ossements de géants du passé. Les légendes parlent de Léviathans qui nageaient dans les mers autrefois. Atteignant même plusieurs centaines de mètres de longueur."
    },
    arzmania: {
        title: "Arzmania",
        description: "Arzmania est la capitale et plus grande métropole de toutes les terres. Elle y abrite tout les peuples du globe même si ces habitants sont majoritairement des humains. La ville est entourée d'une première muraille défensive. Au delà de la première muraille se dresse les secteurs agricoles de la ville qui s'étendent sur des kilomètres, parfois parsemés de petits villages jumelés à Arzmania. La deuxième muraille englobe tout ça et fait plusieurs centaines de kilomètres de circonférence afin de protéger toute cette région. <br><br> Largement peuplé avec d'admirables bâtisse comme des moins impressionnantes, Arzmania est le berceau de l'innovation, la création et la culture. Sa place centrale constituant un véritable forum où diverse personnes et peuples se rassemblent pour discuter, échanger et commercer. <br> C'est une ville développée qui jouit d'une économie qui fonctionne et de personnes vivant en paix. <br><br> Mais bien entendu, chaque paradis ont droit à leur zone d'ombre. Dans les quartiers abritant les classes sociales les plus pauvres, le commerce illégal, le marché noir et la vente d'esclaves sont omniprésents. <br> Il y a aussi une guilde d'assassins qui sévit dans les bas fonds de la capitale. Ils profitent de l'insalubrité de ses quartiers pour se fondre dans la masse et se cacher des forces de l'ordres qui n'osent pas vraiment s'aventurer dans ce coin de la ville. <br><br> Le deuxième mur est tout simplement gigantesque, il marque la frontière entre la ville d'Arzmania et ses alentours avec le reste du monde. <br> Entre le premier et le deuxième mur se dressent des champs à perte de vue ainsi que des petits villages agricoles jumelés à la capitale et ainsi sous la protections de gardes du royaume. <br> Si le royaume doit intervenir en dehors de ces murs, ils envoient l'armée."
    },
    mesthoman: {
        title: "Mesthoman",
        description: "Mesthoman est la ville des Strix, elle est située sur l'archipel des rochers volants. C'est une véritable ville aérienne, les rochers tiennent en lévitation pour une raison inconnue. <br> Étrangement, il y a tout de même de la terre juste en bas, l'apparition de ces rochers volants sont ainsi un des mystères les plus tenaces des terres d'Arzmania. <br><br> Quand les Strixs ne se déplacent pas avec leurs ailes, ils aiment le faire avec des bateaux volants qui leur servent à se déplacer d'îles en îles. Il y a donc un port des airs où les engins volants peuvent s'amarrer tranquillement. <br> Le centre de l'île principale est surplombé par une immense église, les Strixs ont pour habitude de prier au nom des Anges disparus et ont créés un immense édifice pour leur rendre hommage. Se considérant comme l'espèce la plus proches de nos regrettés Anges. Leurs ailes étant semblables ainsi que leur volonté de vive dans la paix la plus totale. <br><br> Juste en bas de l'île principale de l'archipel volant, se trouve une grande prison où sont retenus tout les criminels de partout sur le globe. Quelque soit le peuple ou le crime commis, ces derniers sont tous enfermés dans la même prison, gardée par des Strixs qui sont désignés pour garder la prison durant toute leur vie."
    },
    rogrok: {
        title: "Rogrok",
        description: "Rogrok est la ville des Magmariens, construite à partir de roches volcaniques, elle est située dans une vallée entourée par une chaîne de volcans et de montagnes arides. <br> C'est une ville connue pour abriter les forgerons les plus talentueux de toutes les terres d'Arzmania, et aussi les bains chauds où les touristes ainsi que les habitants aiment venir se relaxer. <br> Il y a aussi un grande arène où des champions du monde entier viennent s'affronter dans des tournois amicaux que les magmariens suivent attentivement comme s'il s'agissait d'un sport. <br><br> Les forges sont les commerces les plus répandus dans la ville de Rogrok. De nombreux Magmariens apprennent tôt l'art de forger le métal afin de créer des armes et des armures. Les environs volcaniques étant riches en minéraux tels que le fer, l'or, l'argent et même des diamants. <br> Les forgerons sont donc des individus respectés dans la société magmarienne et reconnus partout dans le monde pour leurs talents. <br><br> Certains bâtiments sont réservés à une entreprise de bains de lave, spa et bains d'eau chaude pour les touristes. <br> Ils sont reconnus comme des lieux de détente ultime dans la ville et sont régulièrement fréquentés par les habitants qui les utilises comme d'énièmes lieux de rassemblement où ils peuvent discuter de tout et de rien dans des bains. <br> Bien entendu, les autres peuples ne peuvent pas survivre à un plongeon tête piquée dans la lave en fusion, c'est pour cela qu'il existe aussi des bains remplis d'eau chaude."
    },
    itris: {
        title: "Itris",
        description: "Itris est la capitale du continent d'Arasil, c'est une grande métropole assez avancée adoptant une architecture plutôt orientale. <br> Siège du palais de la reine, elle représente le pouvoir ainsi que le progrès. <br><br> Une des plus nette représentation de ce progrès réside dans le quartier scientifique. Il y a un nombre de laboratoires ahurissant, surplombé du grand observatoire de la ville, les Arasiliens étant très friands d'astronomie. <br> Ces derniers s'amusent ainsi à cartographier le ciel et à faire d'importantes découvertes qui pourraient expliquer les origines du monde. <br> C'est ici que les plus gros progrès technologiques opèrent. Les magicautomates, les véhicules rudimentaires ainsi que l'étude des sorts. <br><br> En dehors de la ville, plus loin encore que le désert de Koald, se trouve la Jungle Millénaire. Un épais enchevêtrement de très dense végétation qui cache parfois d'étranges ruines qui sont considérées comme très anciennes. <br> Les rumeurs racontent que des esprits résident en ces lieux. Les aventuriers les plus téméraires, explorant ces ruines avec fascination, et les érudits de magie venant méditer dans ces temples ancestraux en quête de réponses."
    },
    grottes: {
        title: "Grottes d'Asteros",
        description: "Les Grottes d'Asteros sont un immense réseaux de grottes situé en dessous de la forêt magique de Galadhbo. Grand, spectaculaire et tentaculaire, ces grottes sont presques aussi grandes qu'un véritable pays de la surface. <br> Elle est ainsi habitée en majorité par les Efles Obscurs, mais on peut aussi y trouver tout un tas de guildes criminelles telles que la célèbre guilde des assassins. <br><br> Les conditions de vies ne sont pas les meilleures du royaume. Violences, esclavagisme, vols, meurtres et trafics illégaux sont monnaie courante. Mais le peuple des Elfes Obscurs parvient tout de même à survivre et à proliférer au sein des grottes d'Astretos. <br> Quasiment toutes les galeries non loin de la surface ont été aménagées pour y vivre. Plus nous nous enfonçons, plus les habitations deviennent sombres et rares. <br><br> Bien l'immensité des ces galerie, la grande partie des grottes d'Asteros demeurent inexplorées. Tout un tas de rumeurs à propos de créatures mystérieuses et de mauvais esprits se propagent parmi les explorateurs qui s'aventurent dans les entrailles de la terre. Nul ne sait si les grottes ont une fin et si ils sont réellement les seuls et uniques habitants des profondeurs."
    },
    plaine: {
        title : "Plaine Féerique",
        description : "La Plaine Féerique est un lieu magnifique peuplé par les êtres magiques que sont les fées. Ici, la végétation y est reine et elle vit en harmonie avec les animaux qui la peuplent. <br> Il y fait bon vivre, la température est bien souvent très agréable et le vent semble même s'adapter au habitants. <br> Le village où habitent les fées se trouve au centre même de la plaine. Les maisons fabriquées à partir de bois, de plantes et de champignons. <br><br> La plaine est réputée pour avoir une végétation et un écosystème unique en son genre. Des variétés de plantes jamais vues, des animaux au capacités étonnantes ou bien encore des plantes géantes. Le trèfle à quatre feuilles qui sert de mairie du village en est un parfait exemple avec les champignons géants. <br> La magie baigne aussi dans les lieux, elle est en revanche bien plus lumineuse et bienveillante que ce que l'on peut retrouver dans la forêt primordiale de Galadhbo. <br><br> Plus en profondeur, entre la lisière de la forêt et la plaine féerique, se trouve la rivière argentée. C'est un lieu unique où la nature semble venir d'une autre planète. Les feuilles des arbres sont de toutes les couleurs et une rivière composée d'une eau scintillante. <br> De nombreuse histoires entourent l'origine de cette eau. Certains parlent du dernier vestige du peuple des anges, d'autres essayent de l'étudier afin de trouver une explication. <br> Cette eau à comme particularité de pouvoir soigner toute les maladies qui existent. Le seul problème étant que lorsqu'elle est mise dans une gourde, ou tout autre récipient, celle-ci redevient un liquide tout à fait ordinaire. Cela oblige donc de la boire à la source pour qu'elle fonctionne.",
    },
};

function showRegion(regionKey) {
    const region = regions[regionKey];
    document.getElementById('region-title').textContent = region.title;
    document.getElementById('region-description').innerHTML = region.description;
    document.getElementById('region-info').classList.remove('hidden');
    
    document.getElementById('region-info').scrollIntoView({
        behavior: 'smooth',
        block: 'nearest'
    });
}

document.querySelectorAll('.zone').forEach(zone => {
    zone.addEventListener('click', function() {
        const regionKey = this.getAttribute('data-region');
        showRegion(regionKey);
    });
});

document.querySelector('.close-btn').addEventListener('click', function() {
    document.getElementById('region-info').classList.add('hidden');
    document.getElementById('exit').scrollIntoView({
        behavior: 'smooth',
        block: 'nearest'
    });
});
